"""Keras code generation (phase 17).

The fast tests assert generated source exactly — codegen is deterministic, so
a golden string is a meaningful contract rather than a brittle one. The
`slow` tests import the generated module under TensorFlow and build it, which
is the only check that proves the analytic shape pass agrees with reality.
"""

import pytest

from app.ml.architecture.emit_keras import EmitError, emit_module
from app.ml.architecture.graph import build_graph
from app.ml.architecture.shapes import infer_shapes
from app.ml.architecture.llm_presets import PRESETS_BY_ID
from app.ml.architecture.templates import TEMPLATES, chain, edge, node
from app.schemas import ArchitectureGraph


def render(graph: ArchitectureGraph, *, name="Test model", num_classes=2, **kwargs) -> str:
    resolved = build_graph(graph)
    shapes, _params, _issues = infer_shapes(resolved, num_classes)
    return emit_module(
        resolved, shapes, architecture_name=name, default_num_classes=num_classes, **kwargs
    )


def tiny_cnn() -> ArchitectureGraph:
    return ArchitectureGraph(
        nodes=[
            node("in", "input", shape="8,8,3"),
            node("conv", "conv2d", filters=4, kernel_size=3, activation="relu"),
            node("gap", "global_avg_pool2d"),
            node("head", "dense", units_from_dataset=True, activation="softmax"),
            node("out", "output"),
        ],
        edges=chain("in", "conv", "gap", "head", "out"),
    )


def test_generated_source_matches_the_golden_output():
    code = render(tiny_cnn(), name="Tiny CNN", architecture_id="arch_test", version=3)

    assert code == '''\
# Generated by Orinth from architecture 'Tiny CNN' (arch_test, v3).
# Regenerated from the visual graph on every export, compile, and training
# run — edits made here are not read back into the studio.

import tensorflow as tf


def build_model(num_classes: int = 2) -> tf.keras.Model:
    """Build the 'Tiny CNN' architecture as a Keras model."""

    x_input_1 = tf.keras.Input(shape=(8, 8, 3), name="x_input_1")
    x_conv2d_1 = tf.keras.layers.Conv2D(4, 3, strides=1, padding="same", activation="relu", name="x_conv2d_1")(x_input_1)
    x_global_avg_pool2d_1 = tf.keras.layers.GlobalAveragePooling2D(name="x_global_avg_pool2d_1")(x_conv2d_1)
    x_dense_1 = tf.keras.layers.Dense(num_classes, activation="softmax", use_bias=True, name="x_dense_1")(x_global_avg_pool2d_1)
    return tf.keras.Model(
        inputs=x_input_1,
        outputs=x_dense_1,
        name="tiny_cnn",
    )


if __name__ == "__main__":
    build_model().summary()
'''


def test_generation_is_deterministic_across_node_declaration_order():
    """Byte-identical output for the same graph is what makes exported code diffable."""

    graph = tiny_cnn()
    shuffled = ArchitectureGraph(
        nodes=list(reversed(graph.nodes)), edges=list(reversed(graph.edges))
    )

    assert render(shuffled, name="Tiny CNN") == render(graph, name="Tiny CNN")


def test_dense_head_emits_num_classes_rather_than_a_literal():
    """The same architecture must retrain against a dataset with a different label count."""

    code = render(tiny_cnn())

    assert "tf.keras.layers.Dense(num_classes," in code


def test_dense_with_a_fixed_unit_count_emits_the_literal():
    graph = tiny_cnn()
    graph.nodes[3] = node("head", "dense", units=17, activation="softmax")

    assert "tf.keras.layers.Dense(17," in render(graph)


def test_output_node_emits_no_layer_and_forwards_its_input():
    code = render(tiny_cnn())

    assert "x_output_1" not in code
    assert "outputs=x_dense_1," in code


def test_merge_node_applies_to_a_list_of_inputs():
    graph = ArchitectureGraph(
        nodes=[
            node("in", "input", shape="8,8,3"),
            node("a", "conv2d", filters=4, kernel_size=1),
            node("b", "conv2d", filters=4, kernel_size=1),
            node("sum", "add"),
            node("gap", "global_avg_pool2d"),
            node("out", "output"),
        ],
        edges=[
            edge("in", "a"),
            edge("in", "b"),
            edge("a", "sum"),
            edge("b", "sum"),
            *chain("sum", "gap", "out"),
        ],
    )

    code = render(graph)

    assert 'tf.keras.layers.Add(name="x_add_1")([x_conv2d_1, x_conv2d_2])' in code


def test_bidirectional_wraps_the_recurrent_layer():
    graph = ArchitectureGraph(
        nodes=[
            node("in", "input", shape="16"),
            node("embed", "embedding", input_dim=100, output_dim=8),
            node("rnn", "lstm", units=4, bidirectional=True),
            node("head", "dense", units=2),
            node("out", "output"),
        ],
        edges=chain("in", "embed", "rnn", "head", "out"),
    )

    code = render(graph)

    assert (
        "tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(4, return_sequences=False, "
        'dropout=0.0), name="x_lstm_1")' in code
    )


def test_pooling_omits_strides_when_it_should_match_the_pool_size():
    graph = ArchitectureGraph(
        nodes=[
            node("in", "input", shape="8,8,3"),
            node("pool", "max_pool2d", pool_size=2, strides=0),
            node("gap", "global_avg_pool2d"),
            node("out", "output"),
        ],
        edges=chain("in", "pool", "gap", "out"),
    )

    code = render(graph)

    assert "strides=" not in code.split("MaxPooling2D")[1].split(")")[0]


def test_backbone_is_constructed_without_a_name():
    """`tf.keras.applications` derives its weights download URL from the model name.

    Naming a backbone after its canvas node sends Keras looking for
    `<node>_notop.h5`, and the ImageNet download 403s.
    """

    graph = ArchitectureGraph(
        nodes=[
            node("in", "input", shape="96,96,3"),
            node("backbone", "pretrained_backbone", application="MobileNetV2", pooling="avg"),
            node("head", "dense", units=2),
            node("out", "output"),
        ],
        edges=chain("in", "backbone", "head", "out"),
    )

    code = render(graph)
    application_call = code.split("tf.keras.applications.MobileNetV2(")[1].split("), ")[0]

    assert "name=" not in application_call
    assert "input_shape=(96, 96, 3" in application_call
    assert "def apply_backbone(" in code


def test_backbone_helper_is_only_emitted_when_a_backbone_is_used():
    assert "def apply_backbone(" not in render(tiny_cnn())


def test_emitting_a_graph_with_errors_raises_rather_than_producing_broken_code():
    graph = tiny_cnn()
    graph.edges.append(edge("head", "conv"))

    with pytest.raises(EmitError, match="graph with errors"):
        render(graph)


def test_emitting_an_empty_graph_raises():
    with pytest.raises(EmitError):
        render(ArchitectureGraph())


def test_every_template_generates_code():
    for template_id, template in TEMPLATES.items():
        code = render(template.graph, name=template.name, num_classes=3)
        assert "def build_model(" in code, template_id


# The LLM scale presets are blueprints, not local builds — instantiating the
# 70B one would allocate hundreds of gigabytes. Their parameter arithmetic is
# verified analytically in `test_architecture_torch_and_presets.py`; this file
# builds only the templates a workstation can actually hold.
#
# Derived from the preset registry rather than an id prefix: a prefix rule
# missed the named model presets when they landed, and the whole suite OOMed.
BUILDABLE_TEMPLATES = [
    template_id
    for template_id in TEMPLATES
    if template_id not in PRESETS_BY_ID or template_id == "llm_tiny"
]


# --- real TensorFlow builds ------------------------------------------------


@pytest.mark.slow
@pytest.mark.parametrize("template_id", sorted(BUILDABLE_TEMPLATES))
def test_templates_build_under_tensorflow_and_match_the_analytic_pass(
    template_id, tmp_path, build_generated
):
    """The check that keeps `shapes.py` honest.

    Every predicted shape must equal the layer's real output shape, and where
    the parameter estimate is not `None` it must match exactly — an estimate
    that is merely close would hide an arithmetic bug.
    """

    template = TEMPLATES[template_id]
    graph = template.graph.model_copy(deep=True)
    for graph_node in graph.nodes:
        # Build offline: random initialization rather than an ImageNet download.
        if graph_node.type == "pretrained_backbone":
            graph_node.params["weights"] = "none"

    resolved = build_graph(graph)
    shapes, estimate, issues = infer_shapes(resolved, num_classes=3)
    assert not [issue for issue in (*resolved.issues, *issues) if issue.severity == "error"]

    code = emit_module(resolved, shapes, architecture_name=template.name, default_num_classes=3)
    model = build_generated(code, tmp_path, f"generated_{template_id}", num_classes=3)

    # The model's output must match what the analytic pass predicted for the
    # node feeding Output. Asserting `== num_classes` instead would be wrong
    # for any head with a fixed width — an LM head pinned to its own vocabulary
    # does not resize with the dataset, and should not.
    final = resolved.nodes[resolved.output_ids[0]].inputs[0]
    assert model.output_shape[1:] == tuple(shapes[final])
    if estimate is not None:
        assert model.count_params() == estimate

    for node_id in resolved.order:
        predicted = shapes.get(node_id)
        if predicted is None:
            continue
        try:
            layer = model.get_layer(resolved.nodes[node_id].var_name)
        except ValueError:
            # Output nodes and the backbone emit no layer under their own name.
            continue
        assert tuple(layer.output.shape[1:]) == tuple(predicted), node_id


@pytest.mark.slow
def test_generated_module_trains_for_one_step(tmp_path, build_generated):
    """End-to-end proof that a graph-built model is a normal trainable Keras model."""

    import numpy as np

    model = build_generated(render(tiny_cnn(), num_classes=2), tmp_path, "generated_tiny", 2)
    model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

    history = model.fit(
        np.random.rand(8, 8, 8, 3).astype("float32"),
        np.eye(2, dtype="float32")[np.random.randint(0, 2, 8)],
        epochs=1,
        verbose=0,
    )

    assert "loss" in history.history
