"""baseline schema

Revision ID: 3f27d1df389a
Revises: 
Create Date: 2026-07-12 22:46:01.256426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f27d1df389a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('comparison_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_jobs_comparison_id'), ['comparison_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_jobs_dataset_key'), ['dataset_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_jobs_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_jobs_status'), ['status'], unique=False)

    op.create_table('inference_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inference_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inference_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_jobs_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_jobs_status'), ['status'], unique=False)

    op.create_table('inference_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('input_path', sa.Text(), nullable=False),
    sa.Column('overlay_path', sa.Text(), nullable=True),
    sa.Column('image_level_label', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inference_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_project_id'), ['project_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_types', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)

    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('model_family', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('promoted_model_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_model_family'), ['model_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_model_family'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_created_at'))

    op.drop_table('training_jobs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inference_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_model_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_created_at'))

    op.drop_table('inference_runs')
    with op.batch_alter_table('inference_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inference_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_inference_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_inference_jobs_model_id'))
        batch_op.drop_index(batch_op.f('ix_inference_jobs_created_at'))

    op.drop_table('inference_jobs')
    with op.batch_alter_table('evaluation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_jobs_model_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_jobs_dataset_key'))
        batch_op.drop_index(batch_op.f('ix_evaluation_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_evaluation_jobs_comparison_id'))

    op.drop_table('evaluation_jobs')
    # ### end Alembic commands ###
