"""add architectures table

Revision ID: e2fbb1f3b7d0
Revises: 3f27d1df389a
Create Date: 2026-08-02 19:32:00.830065

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2fbb1f3b7d0'
down_revision: str | Sequence[str] | None = '3f27d1df389a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architectures',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('architectures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_architectures_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_architectures_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_architectures_task_type'), ['task_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('architectures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_architectures_task_type'))
        batch_op.drop_index(batch_op.f('ix_architectures_project_id'))
        batch_op.drop_index(batch_op.f('ix_architectures_created_at'))

    op.drop_table('architectures')
    # ### end Alembic commands ###
